/**
 * @overview generated by ghoti-cli
 * @fileoverview Project root
 */

import * as React from 'react';

import { renderRoutes } from 'react-router-config';

export interface IProps {
    match: any;
    history: any;
    location: any;
    route: any;
}

console.log('hello');

class AppRoot extends React.Component<IProps, {}> {
    public render() {
        console.log("hello");
        return renderRoutes(this.props.route.routes);
    }
}

export default AppRoot;
