/**
 * @overview generated by ghoti-cli
 * @fileoverview Route configs
 */

import * as React from 'react';
import * as Pages from '../page/import';

import Root from './root';

export default function (props) {
    const routes = [
        {
            component: Root,
            routes: [
                {
                    component: Pages.main,
                    exact: true,
                    path: '/main',

                },
                {
                    component: Pages.settask,
                    exact: true,
                    path: '/setTask',

                },
                {
                    component: Pages.login,
                    exact: true,
                    path: '/',

                },
                {
                    component: Pages.addtask,
                    exact: true,
                    path: '/addTask',

                },
                {
                    component: Pages.edittask,
                    exact: true,
                    path: '/editTask',

                },
                {
                    component: Pages.register,
                    exact: true,
                    path: '/register',

                },
                {
                    component: Pages.test,
                    exact: true,
                    path: '/test',

                },
                {
                    component: Pages.deluser,
                    exact: true,
                    path: '/deluser',

                },
                {
                    component: Pages.userprofile,
                    exact: true,
                    path: '/userprofile',

                },
                {
                    component: () => <div>Path = /home</div>,
                    path: '/home',
                },
                {
                    component: () => <div>404</div>,
                    path: '*',
                },
            ],
        },
    ];
    return routes;
};
