/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiIcon
 */

import * as React from 'react';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';

export interface IProps {

}

export interface IState {

}

class ComponentGhotiIcon extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div>
            <span>Hello, ComponentGhotiIcon!</span>
        </div>);
    }
}

export default ComponentGhotiIcon;
