/**
* @overview generated by ghoti-cli
* @fileoverview components import file
* You should not edit this file by hand
*/

import ComponentGhotiIcon from './icon.component';

export {
    ComponentGhotiIcon as icon,
};
