/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiChecklist
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';
import * as $ from "jquery";

import Config from '../config/config';

export interface IProps {

}

export interface IState {

}



class PageGhotiChecklist extends React.Component<IProps, IState> {
    state={
        checklist:[]
    }
    public componentDidMount(){
        $.ajax({
            url:"https://rpntechserver.appspot.com/findChecklistByTask?task_id="+localStorage.getItem("currTask"),
            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: (function (result) {
                // console.log(result);
                this.setState({checklist:result});
            }).bind(this),
        })
    }
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div>
           <table className="table">
           <thead>
               {this.state.checklist.map(function(item,key){
                   return(
                    <React.Fragment key={key}>
                    ()
                    {console.log(key)}
                    </React.Fragment>
                   )
               })}
           </thead>
           </table>
        </div>);
    }
}

export default PageGhotiChecklist;
