/**
* @overview generated by ghoti-cli
* @fileoverview page import file
* You should not edit this file by hand
*/

import PageGhotiMain from './main.page';
import PageGhotiAddtask from './addtask.page';
import PageGhotiEdittask from './edittask.page';
import PageGhotiLogin from './login.page';
import PageGhotiSettask from './settask.page';
import PageGhotiRegister from './register.page';
import PageGhotiTest from './test.page';
import PageGhotiDeluser from './deluser.page';
import PageGhotiUserprofile from './userprofile.page';
import PageGhotiOrdertask from './ordertask.page';
export {
    PageGhotiMain as main,
    PageGhotiAddtask as addtask,
    PageGhotiEdittask as edittask,
    PageGhotiLogin as login,
    PageGhotiSettask as settask,
    PageGhotiRegister as register,
    PageGhotiTest as test,
    PageGhotiDeluser as deluser,
    PageGhotiUserprofile as userprofile,
    PageGhotiOrdertask as ordertask,
};
