/**
* @overview generated by ghoti-cli
* @fileoverview page import file
* You should not edit this file by hand
*/

import PageGhotiMain from './main.page';
import PageGhotiAddtask from './addtask.page';
import PageGhotiEdittask from './edittask.page';
import PageGhotiLogin from './login.page';
export {
    PageGhotiMain as main,
    PageGhotiAddtask as addtask,
    PageGhotiEdittask as edittask,
    PageGhotiLogin as login,
};
