/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiMain
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';
import logo from "./logo";
import { ITask, IPage } from './interface';
import * as $ from 'jquery';
import { Table, Column, HeaderCell, Cell } from 'rsuite-table';
import { Redirect } from 'react-router-dom'
import * as ReactDOM from 'react-dom'



import Config from '../config/config';


export interface IProps {
    page: IPage;
    updatePage?: (page: IPage) => void;
    history: any;
}

export interface IState {
}
var jdata: any;



class PageGhotiMain extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
        this.search = this.search.bind(this);
        this.logout = this.logout.bind(this);
        this.addTask = this.addTask.bind(this);

    }

    public componentWillMount() {
        //console.log(localStorage.getItem('Token'));
        $.ajax({
            url: 'https://rpnserver.appspot.com/findAllTasks',
            //url: 'https://rpnserver.appspot.com/userProfile',
            //url: 'http://localhost:8080/login',
            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: (function (data) {
                var items = [];
                console.log(data);
                $.each(data, function (key, val) {
                    items.push("<tr>");
                    items.push("<td id=''" + key +"onclick=''" +"''>" + val.Address + "</td>");
                    items.push("<td id=''" + key + "''>" + val.asset_num + "</td>");
                    items.push("<td id=''" + key + "''>" + val.StartDate + "</td>");
                    items.push("<td id=''" + key + "''>" + val.Username + "</td>");
                    items.push("</tr>");
                });
                $("<tbody/>", { html: items.join("") }).appendTo("table");

            }).bind(this),
        });
    }

    public render() {
        return (<div className="main">
            <div className="title">
                <div style={{
                    display: 'flex',
                    height: '100px',
                    alignItems: 'center',
                    width: '100%'
                }}>
                    <img src={logo} alt="logo" style={{
                        width: '70px',
                        height: '50px',
                    }} />
                    <div style={{
                        flex: 1,
                        paddingLeft: '10px',
                        paddingTop: '20px',
                        display: 'inline',
                        fontSize: '20px',
                        color: 'darkblue',
                        fontWeight: 'bold',
                    }}>
                        Repair and Preservation Network, LLC
                </div>
                    <div style={{
                        marginTop: '20px',
                        marginRight: '20px',
                        textAlign: 'center',
                        width: '30%'

                    }}>
                        <input type="text" id="myInput" placeholder="Search for Addr.." title="Search Task" />
                    </div>
                    <div style={{
                        marginTop: '20px',
                        marginRight: '10px',
                        textAlign: 'right',
                    }}>
                        <button className='link' title='Log out' onClick={this.logout}><ins>Log Out</ins></button>
                    </div>
                </div>
            </div>
            <div className="space">
                <div style={{
                    alignItems: 'center',
                    textAlign: 'center',
                    marginTop: '10px',
                    width: '100%',
                }}>
                    Welcome to Repair and Preservation Network Company!
                </div>
            </div>
            <div className="menu">
                <div style={{
                    margin: '15px',
                }}>
                    <button className="link" title="View Task" onClick={this.changeStatus}><ins>View Task</ins></button>
                </div>
                <div style={{
                    margin: '5px',
                }}>
                    <button className="link" title="Add Task" onClick={this.addTask}><ins>Add Task</ins></button>
                </div>
                <div style={{
                    margin: '5px',
                }}>
                    <button className="link" title="Refresh Task" onClick={this.updateItem}><ins>Refresh</ins></button>
                </div>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Property Address</th>
                        <th>Asset Number</th>
                        <th>Due Date</th>
                        <th>User</th>
                    </tr>
                </thead>
            </table>

        </div >);
    }

    protected updateItem() {
        var temp;
        $.ajax({
            url: 'https://rpnserver.appspot.com/findAllTasks',
            //url: 'http://localhost:8080/login',
            headers: {
                Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpdHkiOiIyIiwiZXhwIjoxNTMxNDA4NjA5LCJ1c2VybmFtZSI6Im5pazAxMDUifQ.HLjqGv9A2zfu99OVxSPQRTXSj1Znv5ygbx_n9ucB65M",
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: function (data) {
                temp = data;
                //this.IProps.key = data;
                console.log(temp);
                console.log(temp[0].Area);


            },
        });
    }


    

    protected search() {

    }

    protected logout() {

    }
    protected changeStatus() {

    }
    protected addTask() {
        this.props.history.push('/addTask');
    }
}

export default PageGhotiMain;
