/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiMain
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';
import logo from "./logo";
import { IItem, IPage } from './interface';

import Config from '../config/config';

export type MMode = 'taskview' | 'addtask';

export interface IProps {
    page: IPage;
    updatePage?: (page: IPage) => void;
    addtask:any;
}

export interface IState {

}

const s = {
    th :{
        border: '1px solid #dddddd',
        textAlign: 'left',
        padding: '8px',
    },
    td :{
        border: '1px solid #dddddd',
        textAlign: 'left',
        padding: '8px',
    },
};

class PageGhotiMain extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
        this.search=this.search.bind(this);
        this.logout=this.logout.bind(this);
        this.addTask=this.addTask.bind(this);
    }

    public render() {
        return (<div className="main">
            <div className="title">
            <div style={{
                display:'flex',
                height: '100px',
                alignItems: 'center',
                width: '100%'
            }}>
                <img src={logo} alt="logo" style={{
                    width: '70px',
                    height: '50px',
                }} />
                <div style={{
                    flex: 1,
                    paddingLeft: '10px',
                    paddingTop: '20px',
                    display: 'inline',
                    fontSize: '20px',
                    color: 'darkblue',
                    fontWeight: 'bold',
                }}>
                    Repair and Preservation Network, LLC
                </div>
                <div style={{
                    marginTop:'20px',
                    marginRight:'20px',
                    textAlign:'center',
                    width:'30%'
                    
                }}>
                <input type="text" id="myInput"  placeholder="Search for Addr.." title="Search Task"/>
                </div>
                <div style={{
                    marginTop:'20px',
                    marginRight:'10px',
                    textAlign:'right',
                }}>
                <button className='link' title='Log out' onClick={this.logout}><ins>Log Out</ins></button>
                </div>
            </div>
            </div>
            <div className="space">
                <div style={{
                    alignItems:'center',
                    textAlign : 'center',
                    marginTop:'10px',
                    width: '100%',
                }}>
                Welcome to Repair and Preservation Network Company!
                </div>
            </div>
            <div className="menu">
                <div style={{
                    margin : '15px',
                }}>
                <button className="link" title="View Task" onClick={this.changeStatus}><ins>View Task</ins></button>
                </div>
                <div style={{
                    margin : '5px',
                }}>
                <button className="link" title="Add Task" onClick={this.addTask}><ins>Add Task</ins></button>
                </div>
            </div>
                <table>
                    <tr>
                        <th>Property Address</th>
                        <th>Asset Number</th>
                        <th>Country</th>
                    </tr>
                    <tr>
                        <td>Alfreds Futterkiste</td>
                        <td>Maria Anders</td>
                        <td>Germany</td>
                    </tr>
                    <tr>
                        <td>Magazzini Alimentari Riuniti</td>
                        <td>Giovanni Rovelli</td>
                        <td>Italy</td>
                    </tr>
                </table>
            
        </div>);
    }

    protected mapItem(value: IItem, index: number): JSX.Element {
        return (<React.Fragment key={index}><tr>
            <td style={(s.td as any)}>
                <div style={{
                    padding: '3px',
                }}>{index + 1}.&nbsp;{value.propaddr}</div>
            </td>
            <td style={{
                padding: '3px',
                fontWeight: 'bold',
            }}>
                <div style={{ display: 'flex' }}>
                    <div>$</div>
                    <div style={{ flex: 1, textAlign: 'right' }}>
                        {value.assetnum ? value.assetnum.toFixed(2) : 0}
                    </div>
                </div>
            </td>
        </tr>
        </React.Fragment>);
    }

    protected search(){
        
    }

    protected logout(){

    }
    protected changeStatus(){

    }
    protected addTask(){
        this.props.addtask.push('/addtask');
    }
}

export default PageGhotiMain;
