/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiPrintedit
 */

import * as React from 'react';
import * as $ from "jquery";
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';
import rlogo from './repairbaseLogo';
import logo from './logo';

import Config from '../config/config';

export interface IProps {
    history: any;
}

export interface IState {

}

class PageGhotiPrintedit extends React.Component<IProps, IState> {
    state = {
        //page:null,
        Address: '',
        Area: '',
        BillTo: '',
        City: '',
        CompletionDate: '',
        Desc: '',
        DescCN: '',
        Invoice: '',
        DueDate: '',
        InvoiceDate: '',
        Item: [],
        LBNum: '',
        Note: '',
        Stage: '',
        StartDate: '',
        Stories: '',
        TotalCost: '',
        TotalImage: 0,
        Year: '',
        AssetNum: '',
        uploadLink: '',
        Tax: '',
        Before: [],
        During: [],
        After: [],
        Username: [],
        alluser: [],
        TaskStatus: '',
        Client: '',
        // test: 'test',
        // x: "a",
        CheckList: [],
        Comment: "",
        Markers: [],
        currImgID: ""


        //data: [],
    };
    public componentDidMount() {
        // console.log(localStorage.getItem("currStage"));
        $.ajax({
            url: 'https://rpntechserver.appspot.com/findTaskById?task_id=' + localStorage.getItem("currTask"),
            //url: 'http://localhost:8080/login',
            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: (function (result) {
                //let test: IPage=JSON.parse(result.toString);
                // console.log(test);
                console.log(result);
                // console.log(JSON.stringify(result));
                this.setState({ Address: result.Address });
                this.setState({ Area: result.Area });
                this.setState({ BillTo: result.BillTo });
                this.setState({ City: result.City });
                this.setState({ CompletionDate: result.CompletionDate });
                this.setState({ Desc: result.Desc });
                this.setState({ DescCN: result.DescCN });
                this.setState({ Invoice: result.Invoice });
                this.setState({ DueDate: result.DueDate });
                this.setState({ InvoiceDate: result.InvoiceDate });
                this.setState({ Item: result.ItemList });
                this.setState({ LBNum: result.KeyCode });
                this.setState({ Note: result.Note });
                this.setState({ Stage: result.Stage });
                this.setState({ StartDate: result.StartDate });
                this.setState({ Stories: result.Stories });
                this.setState({ TotalCost: result.TotalCost });
                this.setState({ TotalImage: result.TotalImage });
                this.setState({ Year: result.Year });
                this.setState({ AssetNum: result.asset_num });
                this.setState({ uploadLink: result.upload_link });
                this.setState({ Tax: result.Tax });
                this.setState({ Username: result.Username });
                this.setState({ Client: result.Client });
                this.setState({ TaskStatus: result.TaskStatus });
                this.setState({ CheckList: result.CheckList });
                this.setState({ Comment: result.Comment });

                //this.setState({ })                


            }).bind(this),
        });
        
    }
    public constructor(props) {
        super(props);
    }



    public render() {
        let taxTotal = 0;
        let TotalAmount = 0;
        for (let i of this.state.Item) {
            TotalAmount += (i.Amount ? i.Amount : 0);
            taxTotal += (i.Tax ? i.Tax : 0);
        }
        return (<div>
            <div style={{
                height: "3%",
                backgroundColor: "lightblue"
            }}>
                <button id="backbtn" onClick={() => {
                    this.props.history.push("/edittask")
                }}>back</button>
            </div>

            {this.showTable(taxTotal, TotalAmount)}
        </div>);
    }

    protected mapPicture(picture: any[], desc: string, descCN: string){
        return (
            picture.map(function (item, key) {
                return (
                    // <div>
                    //     <div>
                    //         <img style={{
                    //             width: '25%',
                    //             height: 'auto',

                    //             padding: '3px'
                    //         }}
                    //             src={item.Src}
                           
                    //         />
                    //     </div>
                    //     <div>
                    //         {desc}{descCN ? "/" + descCN : ""}
                    //     </div>
                    // </div>
                    
                    <td style={{
                        // display:"table-cell"
                        width:"50%"
                        }}>
                        <img style={{
                            width: '100%',
                            height: 'auto',
                            // display:"block",
                            

                            padding: '3px'
                        }}
                            src={item.Src}

                        /><div style={{
                            margin:"auto",
                            wordWrap: "break-word"
                        }}>124444444444444aaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa444444444444444443</div>
                        
                    </td>
                    
                )
            }.bind(this))
        )
    }

    

    protected showTable(taxTotal, TotalAmount) {
        if (this.state.Stage === "0") {
            return (
                <React.Fragment>
                    <table id="stage0">
                        <tr ><td style={{ width: "25%" }}>Property Address:</td> <td>{this.state.Address}</td></tr>
                        <tr><td style={{ width: "25%" }}>Asset Number</td> <td>{this.state.AssetNum}</td></tr>
                        <tr><td style={{ width: "25%" }}>Start Date</td><td>{this.state.StartDate}</td></tr>
                        <tr><td style={{ width: "25%" }}>Due Date</td><td>{this.state.DueDate}</td></tr>
                        <tr><td style={{ width: "25%" }}>City/State/Zip Code </td><td>{this.state.City}</td></tr>
                        <tr><td style={{ width: "25%" }}>Description </td><td>{this.state.Desc}</td></tr>
                        <tr><td style={{ width: "25%" }}>Lock Box Number</td> <td>{this.state.LBNum}</td></tr>
                    </table>
                </React.Fragment>
            )
        }
        else if (this.state.Stage === "1") {
            return (
                <React.Fragment>
                    <div style={{
                        float: "left",
                        marginLeft: "20px",
                        width: "45%",
                        height: "10px",
                        // backgroundColor:"blue"
                    }}>
                        <div style={{
                            flex: 1,
                            paddingLeft: '10px',
                            paddingTop: '20px',
                            display: 'inline',
                            fontSize: '20px',
                            color: 'darkblue',
                            fontWeight: 'bold',
                        }}>
                            <div>
                                <img src={rlogo} alt="logo" style={{
                                    width: 'auto',
                                    height: '80px',
                                }} />
                            </div>
                        </div>
                        <div style={{ 
                display: 'flex',
                
                }}>
                
                <img src={logo} alt="logo" style={{
                    width: '70px',
                    height: '60px',
                }} />
                
                <div style={{ flex: 3,
                    paddingLeft:'10px' ,
                
                }}>
                <div style={{
                    flex: 1,
                    paddingTop:'20px',
                    display: 'inline',
                    fontSize: '20px',
                    color: 'darkblue',
                    fontWeight: 'bold',
                }}>
                    Document Presented by<br/>
                    Repair and Preservation Network, LLC<br/>
                </div>
                    10 Old Mamaroneck Road Unit 1A.<br />
                    White Plains, NY 10605<br />
                    Phone: (866)-766-8880
                    
                </div>
                </div>
                    </div >


                    <div style={{ marginTop:"10px", width: "55%", float: "right" }}>
                        <h1 style={{
                            color:"powderblue", 
                            marginLeft: "10px", 
                            textAlign:"center", 
                            fontSize: '45px',
                            fontWeight: 'bold', 
                    }}>BID</h1>
                        <table id="stage1" style={{
                            // float: "right",
                            // width: "45%",
                            // marginRight: "10px",
                            marginTop: "20px"
                        }}>
                            <tr><td style={{ width: "25%" }}>Property Address:</td> <td>{this.state.Address}</td></tr>
                            <tr><td style={{ width: "25%" }}>Asset Number:</td> <td>{this.state.AssetNum}</td></tr>
                            <tr><td style={{ width: "25%" }}>Start Date:</td><td>{this.state.StartDate}</td></tr>
                            <tr><td style={{ width: "25%" }}>Due Date:</td><td>{this.state.DueDate}</td></tr>
                            <tr><td style={{ width: "25%" }}>City/State/Zip Code: </td><td>{this.state.City}</td></tr>
                            <tr><td style={{ width: "25%" }}> Description:</td><td>{this.state.Desc}</td></tr>
                            <tr><td style={{ width: "25%" }}>Lock Box Number:</td> <td>{this.state.LBNum}</td></tr>
                        </table>
                    </div>
                    <div style={{
                        marginTop:"400px", 
                        marginLeft:"30px"
                    }}>
                    <table style={{margin:"auto"}}>
                        <thead>
                            <tr>
                                <th>Category</th>
                                <th>Item</th>
                                <th>Description</th>
                                <th>Amount</th>
                                
                            </tr>
                        </thead>
                        <tbody>{this.state.Item.map(function (item, key) {
                            return (
                                <React.Fragment key={key}>
                                    <tr>
                                        <td>{item.Cate}</td>
                                        <td>{item.Item}</td>
                                        <td>{item.description}<div>{item.Comments}</div></td>
                                        <td>{item.Cost}</td>
                                        
                                    </tr>
                                    {/* <td
                                        style={{
                                            border: "none",
                                            borderCollapse: "collapse",
                                        }}
                                    ></td> */}
                                    <tr><td style={{ borderLeftColor: "white", borderBottomColor: "white" }}>&nbsp;</td><th colSpan={6}>Before </th></tr>
                                    <tr><td style={{ borderLeftColor: "white", borderBottomColor: "white" }}>&nbsp;</td><td colSpan={6}>{this.mapPicture(item.Before, item.description, item.description_cn)}</td></tr>
                                    <tr><td style={{ borderLeftColor: "white", borderBottomColor: "white" }}>&nbsp;</td><th colSpan={6}> During </th></tr>
                                    <tr><td style={{ borderLeftColor: "white", borderBottomColor: "white" }}>&nbsp;</td><td colSpan={6}>{this.mapPicture(item.During, item.description, item.description_cn)}</td></tr>
                                    <tr><td style={{ borderLeftColor: "white", borderBottomColor: "white" }}>&nbsp;</td><th colSpan={6}> After </th></tr>
                                    <tr><td style={{ borderLeftColor: "white", }}>&nbsp;</td><td colSpan={6}>{this.mapPicture(item.After, item.description, item.description_cn)}</td></tr>

                                </React.Fragment>
                            )
                        }.bind(this))}
                            <tr><td colSpan={2}>HOA: Sales tax {this.state.Tax} %</td><td colSpan={5}>TotalTax: ${taxTotal}</td></tr>
                            <tr><td colSpan={6}>Total Amount: ${TotalAmount} </td></tr>
                        </tbody>
                        {/* <tbody>
                            {this.state.Item.map(this.mapShowItem)}
                        </tbody> */}
                    </table>
                    </div>
                    

                </React.Fragment>
            )
        }
        else if (this.state.Stage === "2") {
            return (
                <React.Fragment>
                    <table id="stage2">
                        <tr><td style={{ width: "25%" }}>Property Address:</td> <td>{this.state.Address}</td></tr>
                        <tr><td style={{ width: "25%" }}>KeyCode/LockBoxNum</td><td>{this.state.LBNum}</td></tr>
                        <tr><td style={{ width: "25%" }}>Due Date</td><td>{this.state.DueDate}</td></tr>
                        <tr><td style={{ width: "25%" }}>City/State/Zip Code </td><td>{this.state.City}</td></tr>
                        <tr><td style={{ width: "25%" }}>UploadLink</td><td>{this.state.uploadLink}</td></tr>
                    </table>
                </React.Fragment>
            )
        }
        else {
            return (
                <React.Fragment>
                    <table id="stage3">
                        <tr><td style={{ width: "25%" }}>Property Address:</td> <td>{this.state.Address}</td></tr>
                        <tr><td style={{ width: "25%" }}>Invoice Number</td> <td>{this.state.Invoice}</td></tr>
                        <tr><td style={{ width: "25%" }}>CompletionDate</td><td>{this.state.CompletionDate}</td></tr>
                        <tr><td style={{ width: "25%" }}>Invoice Date</td><td>{this.state.InvoiceDate}</td></tr>
                        <tr><td style={{ width: "25%" }}>BillTo </td><td>{this.state.BillTo}</td></tr>
                    </table>
                </React.Fragment>
            )
        }
    }
}

export default PageGhotiPrintedit;
